### ISSUE TITLE
Fix indentation and use of whitespace

### ISSUE THREAD

**Issue by jerryjohnjacob** [geona-george/calculator.github.io#2]
There is no indentation rule followed right now for any of the code. Please make sure to look up and follow any of the recommended indentation rules and guidelines for whitespace usage for all three types of code.

Some examples of areas with issues:

![Screenshot 2020-11-12 at 2 11 18 PM](https://user-images.githubusercontent.com/4962432/98916361-156b3d80-24f1-11eb-9991-435a5103a2ae.png)
-------------
![Screenshot 2020-11-12 at 2 11 23 PM](https://user-images.githubusercontent.com/4962432/98916370-18662e00-24f1-11eb-93ed-128a3ab39fed.png)
-------------
![Screenshot 2020-11-12 at 2 11 42 PM](https://user-images.githubusercontent.com/4962432/98916374-1a2ff180-24f1-11eb-8ec9-cad5f7a41c2c.png)
-------------
![Screenshot 2020-11-12 at 2 11 55 PM](https://user-images.githubusercontent.com/4962432/98916379-1b611e80-24f1-11eb-887b-63f70bb3539a.png)
-------------
![Screenshot 2020-11-12 at 2 12 04 PM](https://user-images.githubusercontent.com/4962432/98916383-1c924b80-24f1-11eb-9f39-2f908eebb64a.png)

**Comment by geona-george** [comment]
okay sir, I will look into it

**Comment by geona-george** [comment]
Solved this issue. Please check into it

**Comment by jerryjohnjacob** [comment]
Very nice! 👏
