### ISSUE TITLE
Refactor to introduce modularization

### ISSUE THREAD

**Issue by jerryjohnjacob** [geona-george/calculator.github.io#3]
The code is looking a lot like a script that runs from beginning to end. Try to find ways to modularize it to improve readability and introduce some structure.

**Comment by geona-george** [comment]
Okay, sir but I have a doubt about this. Should I make the script in sections and write some lines(using //) to make each section understandable to the viewer, is that what you mean?

**Comment by jerryjohnjacob** [comment]
Your code should ideally be self-explanatory and shouldn't need comments. In complicated use cases, that is not always possible, but we shouldn't resort to that here.

The idea is to improve readability as well as introduce some structure to the code. You may choose to use multiple script files depending on the organizational structure you have in mind, but it's not a necessity. Part of my ask is for you to come up with said structure.

You can use any JS features to your advantage - functions, objects, etc - to make life easier for you.
