### ISSUE TITLE
Support negative "extra" payments

### ISSUE THREAD

**Issue by jerryjohnjacob** [geona-george/calculator.github.io#4]
Loany McLoany Funds was delighted you provided them with an option to increase the monthly payments. They were asking whether it'd be possible to to allow negative amounts there, which would reduce the monthly payments. Can you add that functionality?

**Comment by geona-george** [comment]
Sir do you mean that I have to add a negative amortization functionality?

**Comment by jerryjohnjacob** [comment]
No, not negative amortization. The extra payments field now allows us to increase the monthly payments from the default calculated value. Update it such that it can take a negative figure to decrease the monthly payments.

**Comment by geona-george** [comment]
I have updated the new functionality.

**Comment by jerryjohnjacob** [comment]
It's working, nice!
