### ISSUE TITLE
Interest-only radio buttons can both be selected at the same time

### ISSUE THREAD

**Issue by jerryjohnjacob** [geona-george/calculator.github.io#5]
Please see the screen recording below:

![geona-amort-calc-radio-button-issue](https://user-images.githubusercontent.com/4962432/101589760-18355180-3a0f-11eb-9ad6-1d717447c0fa.gif)

It shouldn't be possible to select both at the same time. When one is selected, the other should automatically get deselected.

**Comment by geona-george** [comment]
i resolved this problem can you please check it?

**Comment by jerryjohnjacob** [comment]
I'm still seeing the issue. Was the fix not pushed to Github?

![Screenshot 2020-12-10 at 9 48 58 AM](https://user-images.githubusercontent.com/4962432/101720994-f7cbcc80-3acc-11eb-9b77-3b07ec2b92ab.png)

**Comment by geona-george** [comment]
Sir did you click calculate , I did an another approach so clicking both
will not work

On 10 Dec 2020 9:49 a.m., "Jerry John Jacob" <notifications@github.com>
wrote:

I'm still seeing the issue. Was the fix not pushed to Github?

[image: Screenshot 2020-12-10 at 9 48 58 AM]
<https://user-images.githubusercontent.com/4962432/101720994-f7cbcc80-3acc-11eb-9b77-3b07ec2b92ab.png>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/geona-george/calculator.github.io/issues/5#issuecomment-742228823>,
or unsubscribe

**Comment by jerryjohnjacob** [comment]
Here's the main problem. If I happen to select Yes, there's no way for me to unselect it and choose No (and vice versa).

![Screenshot 2020-12-11 at 4 00 59 PM](https://user-images.githubusercontent.com/4962432/101893017-27143380-3bca-11eb-95b7-810f0dfd3a10.png)

As I had mentioned, the calculations are individually correct. This is just an issue with the way the radio buttons have been configured.

**Comment by geona-george** [comment]
I understood the problem and have resolved it but I haven't updated it in
GitHub because I have started with modifications and adding functions.
I'm doing what I can do to make it better. Hope I can complete it by coming
Monday.

**Comment by jerryjohnjacob** [comment]
Alright, looking forward to seeing it!

**Comment by jerryjohnjacob** [comment]
Hey Geona! I was just checking in to see if there was any update

**Comment by geona-george** [comment]
No sir I haven't added it. Will do by today

**Comment by geona-george** [comment]
hello sir,
what happened is that the work I did got deleted by mistake and what I
could push was only the completed yes/no radio button and made the site
responsive using bootstrap.

**Comment by jerryjohnjacob** [comment]
I saw the fix, but I noticed a small issue, which I think might be JS you added that's not required. When you choose an option, the other option becomes disabled. Without that, the functionality looks good. I didn't see the site responsiveness - is that not deployed yet?

**Comment by geona-george** [comment]
solved the issue
